CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  balance BIGINT UNSIGNED,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS roles (
  role_type VARCHAR(50) NOT NULL,
  user_id BIGINT NOT NULL UNIQUE,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS cart (
  product_en_name VARCHAR(100) NOT NULL,
  product_ru_name VARCHAR(100) NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  amount INT UNSIGNED NOT NULL,
  user_id BIGINT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS receipts (
  date_of_order VARCHAR(255) NOT NULL,
  product_en_name VARCHAR(100) NOT NULL,
  product_ru_name VARCHAR(100) NOT NULL,
  amount INT UNSIGNED NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  user_id BIGINT NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ingredients (
  id BIGINT NOT NULL AUTO_INCREMENT,
  ingredient_en_name VARCHAR(100) NOT NULL,
  ingredient_ru_name VARCHAR(100) NOT NULL,
  amount INT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS ready_products (
  id BIGINT NOT NULL AUTO_INCREMENT,
  category VARCHAR(50) NOT NULL,
  product_en_name VARCHAR(100) NOT NULL,
  product_ru_name VARCHAR(100) NOT NULL,
  amount INT UNSIGNED NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  ingredient_id BIGINT,
  FOREIGN KEY(ingredient_id) REFERENCES ingredients(id)
);
